jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Python path
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/infra" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install AWS CDK
        run: npm install -g aws-cdk@2

      - name: Install Python dependencies
        working-directory: infra
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip Lambda file
        working-directory: infra/lambda
        run: |
          if [ -f s3_to_glue.py ]; then
            zip ../s3_to_glue.zip s3_to_glue.py
          else
            echo "ERROR: Lambda file s3_to_glue.py not found!" && exit 1
          fi

      - name: CDK Bootstrap
        working-directory: infra
        run: cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }} || echo "Already bootstrapped"

      - name: Deploy CDK stack
        working-directory: infra
        run: cdk deploy ${{ env.CDK_STACK_NAME }} --require-approval never

